<a href="https://colab.research.google.com/github/kossou/Cybersecurity3/blob/main/QuestionPhising.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [17]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0    oaep.diw.go.th        0        0           1          6            0   
1  premiumevents.ge        0        0           0          4            0   
2        rebrand.ly        0        0           0          1            0   
3        uproxx.com        0        0           1          4            0   
4   correios.com.br        0        0           1          4            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           0            0           1   
1             0        0              0           0            1           1   
2             0        0              0           0            0           1   
3             0        1              0           0            1           0   
4             0        0              0           0            1           1   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       0           0            1             0      1  
1           1       0           0            1             1      1  
2           1       0           0            1             0      1  
3           1       0           0            1             0      0  
4           1       0           0            1             0      0

In [18]:
X = data.drop(['Domain', 'Label'], axis=1)

In [19]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          6            0             0   
1        0        0           0          4            0             0   
2        0        0           0          1            0             0   
3        0        0           1          4            0             0   
4        0        0           1          4            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            0           1           1   
1        0              0           0            1           1           1   
2        0              0           0            0           1           1   
3        1              0           0            1           0           1   
4        0              0           0            1           1           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             1  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [20]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [22]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [24]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8076666666666666
Precision: 0.8350963528496401
Recall: 0.8076666666666666
F1 Score: 0.8034363340421365
Confusion Matrix:
[[1436   73]
 [ 504  987]]

SVC Metrics:
Accuracy: 0.8286666666666667
Precision: 0.8632351575875092
Recall: 0.8286666666666667
F1 Score: 0.8242962545605016
Confusion Matrix:
[[1484   25]
 [ 489 1002]]

RandomForestClassifier Metrics:
Accuracy: 0.8593333333333333
Precision: 0.8671207071118454
Recall: 0.8593333333333333
F1 Score: 0.8585097826811322
Confusion Matrix:
[[1408  101]
 [ 321 1170]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.854
Precision: 0.8688096869936501
Recall: 0.854
F1 Score: 0.8524142420427979
Confusion Matrix:
[[1441   68]
 [ 370 1121]]

KNeighborsClassifier Metrics:
Accuracy: 0.8556666666666667
Precision: 0.8684644766609724
Recall: 0.8556666666666667
F1 Score: 0.8543057320837804
Confusion Matrix:
[[1433   76]
 [ 357 1134]]

DecisionTreeClassifier Metrics:
Accuracy: 0.859
Precision: 0.8668528378316872
Recall: 0.859
F1 Score: 0.8581672168437032
Confusion Matrix:
[[1408  101]
 [ 322 1169]]


In [25]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.859333   0.867121  0.859333  0.858510
5  DecisionTreeClassifier  0.859000   0.866853  0.859000  0.858167
4    KNeighborsClassifier  0.855667   0.868464  0.855667  0.854306
3           MLPClassifier  0.854000   0.868810  0.854000  0.852414
1                     SVC  0.828667   0.863235  0.828667  0.824296
0      LogisticRegression  0.807667   0.835096  0.807667  0.803436
